name: The Jenkins - from our side
favicon: null
layout_spectrum: 0.4338899820577353
typography_spectrum: 0.11952984309755266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.10275252792052925
  lightness: 0.38869307353161275
  saturation: 0.057287121657282114
  rhythmicContrast: 0.8922816331032664
purpose: []
