name: The Jenkins - from our side
favicon: null
layout_spectrum: 0.25012
typography_spectrum: 0.11952984309755266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#10110b'
    - '#7a817b'
    - '#675e4d'
    - '#a4a6a3'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.057287121657282114
  rhythmicContrast: 0.5
purpose: []
